# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/a7540286-5238-47e0-818d-02d71a4378b2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6A95-9AC5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
    
  # Mount point for 681.2GB storage partition
  fileSystems."/zz" =
    { device = "/dev/disk/by-uuid/828de0ac-1b32-4381-b276-c12d802fb880";
      fsType = "ext4";
      options = [ "defaults" ];
    };
    
  swapDevices =
    [ { device = "/dev/disk/by-uuid/93c2fa9f-7717-4307-a07e-29af0f9c3358"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
